name: .NET

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 3
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    # - name: run batch file
    #   run: ./cd.bat

    #- name: rmdir package

    - name: pack
      run: dotnet pack error-reporting-csharp --configuration Release -o package

    - name: NuGet Add Source
      run: dotnet nuget add source --username pj-spoelders --password ${GITHUB_TOKEN} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/EXASOL/index.json"
    
    # https://stackoverflow.com/questions/57889719/how-to-push-nuget-package-in-github-actions
    - name: NuGet Push to GH NuGet
      run: dotnet nuget push ./package/*.nupkg -s "github" --api-key ${GITHUB_TOKEN}

